force-app/main/default/objects/Anomaly__c/Anomaly__c.object-meta.xml
<CustomObject>
    <label>Anomaly</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Anomaly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anomaly</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anomaly__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Anomaly</relationshipLabel>
    <relationshipName>Anomaly</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anomaly__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Temperature Anomaly</fullName>
            </value>
            <value>
                <fullName>Pressure Anomaly</fullName>
            </value>
            <value>
                <fullName>Humidity Anomaly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Anomaly__c/fields/Weather__c.field-meta.xml
<CustomField>
    <fullName>Weather__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weather</label>
    <referenceTo>Weather__c</referenceTo>
    <relationshipLabel>Anomaly</relationshipLabel>
    <relationshipName>Anomaly</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AnomalyViewComponentController.cls
public without sharing class AnomalyViewComponentController {
	
    @AuraEnabled
    public static List<Anomaly__c> getAnomalies(){
        return [SELECT Id, Name, Type__c, Reported__c, CreatedDate, City__c, City__r.Name, Weather__c, Weather__r.Name 
                FROM Anomaly__c 
                ORDER BY CreatedDate DESC, Name DESC];
    }
    
    @AuraEnabled
    public static void getCurrentWeather(){
        (new OpenWeatherCalloutService()).getWeatherFromOpenWeather();
    }
    
    @AuraEnabled
    public static void generateAnomalyReport(){
        List<Anomaly__c> unreportedAnomalies = [SELECT Id, Reported__c FROM Anomaly__c WHERE Reported__c = false];
        for(Anomaly__c anomaly : unreportedAnomalies){
            anomaly.Reported__c = true;
        }
        Anomaly_Report__c report = new Anomaly_Report__c(Name = 'Anomaly Report ' + System.now().format('yyyy.MM.dd h:mm a'));
        insert report;
        ContentVersion cv = new ContentVersion();
        cv.Title = report.Name;
        cv.PathOnClient = cv.Title + '.pdf';
        cv.IsMajorVersion = true;
        cv.FirstPublishLocationId = report.Id;
        cv.VersionData = Page.AnomalyReportPage.getcontentAsPdf();
        insert cv;
        update unreportedAnomalies;
    }
}