force-app/main/default/objects/Anomaly__c/Anomaly__c.object-meta.xml
<CustomObject>
    <label>Anomaly</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Anomaly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anomaly</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anomaly__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Anomaly</relationshipLabel>
    <relationshipName>Anomaly</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anomaly__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Temperature Anomaly</fullName>
            </value>
            <value>
                <fullName>Pressure Anomaly</fullName>
            </value>
            <value>
                <fullName>Humidity Anomaly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Anomaly__c/fields/Weather__c.field-meta.xml
<CustomField>
    <fullName>Weather__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weather</label>
    <referenceTo>Weather__c</referenceTo>
    <relationshipLabel>Anomaly</relationshipLabel>
    <relationshipName>Anomaly</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestWeatherTriggerHandler.cls
@IsTest
private class TestWeatherTriggerHandler {

    @TestSetup
    static void makeData(){
        Anomaly_Range_Configuration__c anomalyRangeConfig = TestDataFactory.createAnomalyRangeConfig(
                        'Test Custom Settings',
                        60,
                        760,
                        95,
                        20,
                        700,
                        5);

        insert anomalyRangeConfig;

        City__c city = TestDataFactory.createCity('Test city');
        insert city;
    }

    public static Anomaly_Range_Configuration__c anomalyRangeConfig = Anomaly_Range_Configuration__c.getOrgDefaults();
    public static List <City__c> testCity = [SELECT Name FROM City__c WHERE Name = 'Test city'];

    @IsTest static void checkHumidityAnomaly(){
        Weather__c weatherHumidityAnom = TestDataFactory.createWeatherWithAnomaly('Humidity Anomaly', anomalyRangeConfig, testCity);

        Test.startTest();
        Database.SaveResult result = Database.insert(weatherHumidityAnom, true);
        Test.stopTest();

        List<Anomaly__c> anomaliesList = [SELECT Type__c FROM Anomaly__c];
        System.assert(result.isSuccess());
        System.assertEquals('Humidity Anomaly', anomaliesList.get(0).Type__c);
    }

    @IsTest static void checkPressureAnomaly(){
        Weather__c weatherPressureAnom = TestDataFactory.createWeatherWithAnomaly('Pressure Anomaly', anomalyRangeConfig, testCity);

        Test.startTest();
        Database.SaveResult result = Database.insert(weatherPressureAnom, true);
        Test.stopTest();

        List<Anomaly__c> anomaliesList = [SELECT Type__c FROM Anomaly__c];

        System.assert(result.isSuccess());
        System.assertEquals('Pressure Anomaly', anomaliesList.get(0).Type__c);
    }

    @IsTest static void checkTemperatureAnomaly(){
        Weather__c weatherTemperAnom = TestDataFactory.createWeatherWithAnomaly('Temperature Anomaly', anomalyRangeConfig, testCity);

        Test.startTest();
        Database.SaveResult result = Database.insert(weatherTemperAnom, true);
        Test.stopTest();

        List<Anomaly__c> anomaliesList = [SELECT Type__c FROM Anomaly__c];

        System.assert(result.isSuccess());
        System.assertEquals('Temperature Anomaly', anomaliesList.get(0).Type__c);
    }

    @IsTest static void checkWithoutAnomalies(){
        Weather__c weatherWithoutAnomalies = TestDataFactory.createWeatherWithoutAnomalies(anomalyRangeConfig, testCity);

        Test.startTest();
        Database.SaveResult result = Database.insert(weatherWithoutAnomalies, true);
        Test.stopTest();

        List<Anomaly__c> anomaliesList = [SELECT Type__c FROM Anomaly__c];

        System.assert(result.isSuccess());
        System.assert(anomaliesList.size() == 0);
    }


}