force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/City_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Code__c</fullName>
    <externalId>true</externalId>
    <label>City Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Cloudiness__c.field-meta.xml
<CustomField>
    <fullName>Cloudiness__c</fullName>
    <label>Cloudiness</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Maximum_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Temperature__c</fullName>
    <label>Maximum Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Minimal_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Minimal_Temperature__c</fullName>
    <label>Minimal Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature_Feels_Like__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Feels_Like__c</fullName>
    <label>Temperature Feels Like</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <label>Visibility</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <label>Wind Speed</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpenWeatherCalloutService.cls
public without sharing class OpenWeatherCalloutService{

    private static final String API_KEY = Anomaly_Range_Configuration__c.getOrgDefaults().API_Key__c;
    private static final String ENDPOINT_URL = 'https://api.openweathermap.org/data/2.5/weather';
    private Map<String, City__c> cityCodeToCityMap;

    public OpenWeatherCalloutService(){
        this.cityCodeToCityMap = new Map<String, City__c>();
        for (City__c city : [SELECT id, City_Code__c FROM City__c ]) {
            this.cityCodeToCityMap.put(city.City_Code__c, city);
        }
    }
    @future(callout=true)
    public void getWeatherFromOpenWeather(){
        List<Weather__c> weathersToCreate = new List<Weather__c>();
        for (City__c city : cityCodeToCityMap.values()) {
            Weather__c currentWeather = makeCallout(city.City_Code__c);
            if(currentWeather!=null){
                weathersToCreate.add(currentWeather);
            }            
        }
        system.debug('weathersToCreate size:' + weathersToCreate.size());
        if(!weathersToCreate.isEmpty()){
            insert weathersToCreate;
        }
    }

    public Weather__c makeCallout(String cityId){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(ENDPOINT_URL + '?id=' + cityId + '&appid='+ API_KEY);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if(response.getStatusCode()==200){
            // String responseBody = response.getBody();
            OpenWeatherResponse weatherResponse =(OpenWeatherResponse)JSON.deserialize(response.getBody(), OpenWeatherResponse.class);
            return popularWeatherRecord(weatherResponse, cityId);
        }else {
            system.debug('Status code: ' + response.getStatusCode());
            system.debug('Status: ' + response.getStatus());
            return null;
        }
    }

    public Weather__c popularWeatherRecord(OpenWeatherResponse responseWrap, String cityId){
        Weather__c newWeather = new Weather__c(City__c = cityCodeToCityMap.get(cityid).id
                                                , Visibility__c = responseWrap.visibility
                                                , Temperature__c = responseWrap.main.temp
                                                , Temperature_Feels_Like__c = responseWrap.main.feels_like
                                                , Minimal_Temperature__c = responseWrap.main.temp_min
                                                , Maximum_Temperature__c = responseWrap.main.temp_max
                                                , Pressure__c = responseWrap.main.pressure
                                                , Humidity__c = responseWrap.main.humidity);
        if(responseWrap.wind!=null){
            newWeather.Wind_speed__c = responseWrap.wind.speed;
        }
        if(responseWrap.clouds!=null){
            newWeather.Cloudiness__c = responseWrap.clouds.all;
        }
        return newWeather;
    }

        public class OpenWeatherResponse{
        public Main main;
        public Integer visibility;
        public Clouds clouds;
        public Wind wind; 
    }
    public class Main{
        public Decimal temp; 
        public Decimal feels_like;
        public Decimal temp_min;
        public Decimal temp_max;
        public Integer pressure;
        public Integer humidity;
    }

    public class Clouds{
        public Integer all;
    }
    public class Wind{
        public Decimal speed;
    }
}