force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/City_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Code__c</fullName>
    <externalId>true</externalId>
    <label>City Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Maximum_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Temperature__c</fullName>
    <label>Maximum Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Minimal_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Minimal_Temperature__c</fullName>
    <label>Minimal Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {

    public static Weather__c createweatherWithoutAnomalies(Anomaly_Range_Configuration__c anomalyRangeConfig, List<City__c> city) {
        Weather__c weather = new Weather__c(
                City__c = city.get(0).Id,
                Maximum_Temperature__c = anomalyRangeConfig.Max_Temperature__c,
                Minimal_Temperature__c = anomalyRangeConfig.Min_Temperature__c,
                Pressure__c = anomalyRangeConfig.Max_Pressure__c,
                Humidity__c = anomalyRangeConfig.Max_Humidity__c
        );
        return weather;
    }

    public static Weather__c createWeatherWithAnomaly(String anomaly, Anomaly_Range_Configuration__c anomalyRangeConfig, List<City__c> city){
        Weather__c weather = createweatherWithoutAnomalies(anomalyRangeConfig, city);

        if (anomaly == 'Temperature Anomaly') {
            weather.Maximum_Temperature__c += 10;
            return weather;
        }else if (anomaly == 'Pressure Anomaly') {
            weather.Pressure__c += 10;
            return weather;
        }else if (anomaly == 'Humidity Anomaly') {
            weather.Humidity__c += 10;
            return weather;
        }else {
            System.debug('Weather without anomalies!');
            return weather;
        }
    }

    public static City__c createCity(String name){
        City__c city = new City__c(
                Name = name,
                City_Code__c = '5128581',
                Location__Latitude__s = 40,
                Location__Longitude__s = -74,
                Country__c = 'US');
        return city;
    }

    public static Anomaly_Range_Configuration__c createAnomalyRangeConfig(String name, Decimal maxHumidity,
            Decimal maxPressure, Decimal maxTemper, Decimal minHumidity, Decimal minPressure, Decimal minTemper){
        Anomaly_Range_Configuration__c anomalyRangeSetting = new Anomaly_Range_Configuration__c(
                Name = name,
                Max_Temperature__c = maxTemper,
                Min_Temperature__c = minTemper,
                Max_Pressure__c = maxPressure,
                Min_Pressure__c = minPressure,
                Max_Humidity__c = maxHumidity,
                Min_Humidity__c = minHumidity
        );
        return anomalyRangeSetting;
    }


}