force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Maximum_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Temperature__c</fullName>
    <label>Maximum Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Minimal_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Minimal_Temperature__c</fullName>
    <label>Minimal Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/Temperature_Feels_Like__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Feels_Like__c</fullName>
    <label>Temperature Feels Like</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public with sharing class DataFactory {

    public static Weather__c getWeather(City__c city, Decimal temperature,
            Decimal temperatureFeelsLike, Decimal minTemperature,
            Decimal maxTemperature, Decimal pressure, Decimal humidity){

        Weather__c weather = new Weather__c(
                City__c = city.Id,
                Temperature__c = temperature,
                Temperature_Feels_Like__c = temperatureFeelsLike,
                Minimal_Temperature__c = minTemperature,
                Maximum_Temperature__c = maxTemperature,
                Pressure__c = pressure,
                Humidity__c = humidity
        );
        return weather;
    }

}